import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Clock3, MapPin, Phone } from "lucide-react";
import { Gallery } from "@/components/gallery";
import { MenuBrowser } from "@/components/menu-browser";
import { LocationCard } from "@/components/location-card";
import { locations } from "@/data/locations";
import { photos, galleryCategories } from "@/data/photos";
import { media } from "@/data/media";

const sections = ["about", "menu", "gallery", "locations", "order-online", "catering", "reservations", "contact"] as const;
type Section = typeof sections[number];
const titles: Record<Section, string> = { about: "Our Story", menu: "Our Menu", gallery: "Gallery", locations: "Locations", "order-online": "Order Online", catering: "Catering", reservations: "Reservations", contact: "Contact" };
const subtitles: Record<Section, string> = {
  about: "Good food, good company, and a place for everyone at the table.", menu: "Traditional favorites, made to order and ready to share.", gallery: "A closer look at the flavors that make us, us.", locations: "Three neighborhood restaurants. One warm welcome.", "order-online": "Choose your San Antonio and let us take care of the rest.", catering: "Bring the flavors of San Antonio to your next celebration.", reservations: "Planning a visit? Your neighborhood restaurant is ready to help.", contact: "We would love to hear from you.",
};

export function generateStaticParams() { return sections.map(section => ({ section })); }
export async function generateMetadata({ params }: { params: Promise<{ section: string }> }): Promise<Metadata> {
  const { section } = await params;
  if (!sections.includes(section as Section)) return {};
  return { title: titles[section as Section], description: subtitles[section as Section] };
}

function PageIntro({ section }: { section: Section }) { return <section className="page-intro"><div className="shell"><span className="eyebrow">SAN ANTONIO MEXICAN RESTAURANT / {titles[section].toUpperCase()}</span><h1>{titles[section]}<span className="heading-spark">✳</span></h1><p>{subtitles[section]}</p></div></section>; }

export default async function SectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section: raw } = await params;
  if (!sections.includes(raw as Section)) notFound();
  const section = raw as Section;
  return <><PageIntro section={section}/>
    {section === "about" && <><section className="section"><div className="shell about-grid"><div className="about-image"><Image src="/images/menu/platillos-molcajete-mixto.webp" alt="Molcajete Mixto" fill sizes="(max-width: 800px) 90vw, 45vw" /></div><div className="about-copy"><span className="eyebrow">FAMILY OWNED · ROOTED IN FLAVOR</span><h2>A story served at the table.</h2><p>San Antonio Mexican Restaurant is a family-owned business specializing in authentic Mexican cuisine and fresh, made-to-order dishes. The restaurant&apos;s recipes have been passed down through generations.</p><p>For more than 10 years, San Antonio has shared traditional Mexican flavors and the feeling of home with its guests.</p><Link href="/locations" className="text-link">Come visit us <ArrowUpRight size={18}/></Link></div></div></section><section className="section warm-section"><div className="shell"><p className="big-quote">“The best meals are the ones <em>we share.</em>”</p><div className="about-mosaic"><Image src="/images/menu/tacos-tacos-de-suadero.webp" alt="Tacos de suadero" fill sizes="50vw"/><Image src="/images/menu/desserts-chocoflan.webp" alt="Chocoflan" fill sizes="50vw"/></div></div></section></>}
    {section === "menu" && <section className="section"><div className="shell"><div className="menu-topline"><span className="eyebrow">FRESHLY MADE · ALWAYS SHARED</span><p>Our menu has a little something for every craving. Prices below are a selection from each location&apos;s official online menu.</p></div><MenuBrowser/></div></section>}
    {section === "gallery" && <section className="section"><div className="shell"><div className="menu-topline"><span className="eyebrow">THE COLORS OF OUR KITCHEN</span><p>{photos.length} original restaurant photographs, from breakfast to dessert.</p></div><Gallery photos={photos} categories={galleryCategories}/></div></section>}
    {section === "locations" && <section className="section"><div className="shell"><div className="locations-grid">{locations.map((location, index) => <LocationCard key={location.slug} location={location} index={index}/>)}</div></div></section>}
    {section === "order-online" && <section className="section"><div className="shell"><div className="order-intro"><span className="eyebrow">YOUR FAVORITES, YOUR WAY</span><h2>Choose your location.</h2><p>Ordering opens each restaurant&apos;s official online menu in a new tab. Availability and prices are set by that location.</p></div><div className="order-grid">{locations.map((location, index) => <article key={location.slug} className="order-card"><span>0{index + 1} / {location.neighborhood}</span><h3>{location.name}</h3><p>{location.address}<br/>{location.city}</p><a href={location.orderUrl} target="_blank" rel="noopener noreferrer" className="button button-dark">Order from {location.name.replace("San Antonio ", "")} <ArrowUpRight size={18}/></a></article>)}</div></div></section>}
    {section === "catering" && <><section className="section"><div className="shell catering-page-grid"><div><span className="eyebrow">FOOD FOR THE WHOLE FIESTA</span><h2>Make every gathering memorable.</h2><p>San Antonio offers party packages featuring chivo or pernil, rice, salad and accompaniments. The official promotion page requests at least five days&apos; notice.</p><a href="https://www.sanantoniomr.com/promociones-para-fiestas" target="_blank" rel="noopener noreferrer" className="button button-dark">View official packages <ArrowUpRight size={18}/></a></div><div className="catering-page-image"><Image src="/images/menu/platillos-parrillada-mixta.webp" alt="Parrillada Mixta" fill sizes="(max-width: 800px) 90vw, 50vw" /></div></div></section><section className="section warm-section"><div className="shell"><span className="eyebrow">PARTY PACKAGES</span><h2>Something for every gathering.</h2><div className="package-grid">{[{n:"01",name:"Chivo gathering",price:"$200",detail:"Half tray of chivo, half tray of rice, half tray of salad and consomé."},{n:"02",name:"Chivo celebration",price:"$340",detail:"A tray of chivo and rice, half tray of salad and consomé."},{n:"03",name:"Large chivo celebration",price:"$615",detail:"Two trays of chivo, rice, salad and consomé."},{n:"04",name:"Pernil gathering",price:"$130",detail:"Large pernil, rice, salad, salsa and guacamole."},{n:"05",name:"Pernil celebration",price:"$255",detail:"Two perniles, rice, salad, salsa and guacamole."}].map(pkg => <article className="package-card" key={pkg.n}><span>PACKAGE / {pkg.n}</span><h3>{pkg.name}</h3><p>{pkg.detail}</p><strong>{pkg.price}</strong></article>)}</div><p className="source-note">Package details and listed prices are from the restaurant&apos;s official promotions page. Confirm current availability and final pricing with the restaurant.</p></div></section></>}
    {section === "reservations" && <section className="section"><div className="shell reservation-layout"><div><span className="eyebrow">SAVE A SEAT</span><h2>Let&apos;s get together.</h2><p>For table availability and group visits, please call the location you plan to visit. Online reservations are not currently listed on the official website.</p></div><div className="reservation-list">{locations.map(location => <div key={location.slug}><h3>{location.name}</h3><span>{location.address}, {location.city}</span><a href={`tel:${location.tel}`}><Phone size={17}/>{location.phone}</a></div>)}</div></div></section>}
    {section === "contact" && <section className="section"><div className="shell contact-layout"><div><span className="eyebrow">GET IN TOUCH</span><h2>We&apos;re here for you.</h2><p>Questions about a visit, an order or a gathering? Contact your preferred restaurant directly.</p><a href="https://www.sanantoniomr.com/contact-5" target="_blank" rel="noopener noreferrer" className="text-link">Official contact page <ArrowUpRight size={18}/></a></div><div className="contact-list">{locations.map(location => <article key={location.slug}><h3>{location.name}</h3><p><MapPin size={18}/>{location.address}, {location.city}</p><p><Clock3 size={18}/>{location.hours.map(h => `${h.days}: ${h.time}`).join(" · ")}</p><a href={`tel:${location.tel}`}><Phone size={18}/>{location.phone}</a></article>)}</div></div></section>}
    {media.promotionalVideo && (section === "about" || section === "gallery") && <section className="section"><div className="shell"><video className="promo-video" controls playsInline preload="none" poster="/images/menu/platillos-parrillada-mixta.webp"><source src={media.promotionalVideo} type="video/mp4"/></video></div></section>}
  </>;
}
