import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Star } from "lucide-react";
import { HeroMedia } from "@/components/hero-media";
import { SectionHeading } from "@/components/section-heading";
import { LocationCard } from "@/components/location-card";
import { locations } from "@/data/locations";
import { menuItems } from "@/data/menu";
import { photoById } from "@/data/photos";
import { localizedHref, tr, menuCategoryLabels, categoryLabel, type Locale } from "@/data/i18n";

export function HomeContent({ locale }: { locale: Locale }) {
  const featured = menuItems.filter(item => item.specialty).slice(0, 3);
  const href = (path: string) => localizedHref(locale, path);
  const t = (english: string, spanish: string) => tr(locale, english, spanish);
  return <>
    <section className="hero"><HeroMedia locale={locale}/><div className="shell hero-content"><span className="hero-kicker"><span className="dot"/> {t("PASSAIC & CLIFTON · NEW JERSEY", "PASSAIC Y CLIFTON · NUEVA JERSEY")}</span><h1>{t("Food that", "Comida que")}<br/>{t("feels like", "sabe a")} <em>{t("home.", "hogar.")}</em></h1><p>{t("Traditional Mexican flavors, made fresh and shared with everyone at the table.", "Sabores tradicionales de México, preparados al momento para compartir en la mesa.")}</p><div className="hero-actions"><Link href={href("/menu")} className="button button-cream">{t("Explore the menu", "Explora el menú")} <ArrowUpRight size={19}/></Link><Link href={href("/locations")} className="hero-text-link">{t("Find a location", "Encuentra una sucursal")} <ArrowRight size={18}/></Link></div></div><div className="hero-side-note">{t("THREE LOCATIONS · ONE BIG TABLE", "TRES SUCURSALES · UNA GRAN MESA")}</div><div className="hero-bottom"><span>{t("SCROLL TO EXPLORE", "DESLIZA PARA EXPLORAR")}</span><span>{t("FRESHLY MADE. ALWAYS SHARED.", "RECIÉN HECHO. PARA COMPARTIR.")}</span></div></section>

    <section className="intro-band"><div className="shell intro-inner"><span className="intro-star">✳</span><p>{t("Rooted in tradition.", "Con raíces en la tradición.")} <em>{t("Made to bring people together.", "Hecho para reunirnos.")}</em></p><span>{t("FAMILY OWNED · 10+ YEARS", "NEGOCIO FAMILIAR · MÁS DE 10 AÑOS")}</span></div></section>

    <section className="section story-section"><div className="shell story-grid"><div className="story-photos"><div className="story-photo-main"><Image src="/images/menu/platillos-molcajete-mixto.webp" alt="Molcajete Mixto" fill sizes="(max-width: 800px) 90vw, 40vw" /></div><div className="story-photo-small"><Image src="/images/menu/quesadillas-quesadilla-de-huitlacoche.webp" alt="Quesadilla de huitlacoche" fill sizes="(max-width: 800px) 50vw, 20vw" /></div><span className="story-stamp">{t("MADE", "HECHO")}<br/>{t("WITH", "CON")}<br/>{t("HEART", "AMOR")} ✳</span></div><div className="story-copy"><span className="eyebrow">01 / {t("THE SAN ANTONIO STORY", "LA HISTORIA DE SAN ANTONIO")}</span><h2>{t("A little tradition in", "Un poco de tradición en")} <em>{t("every bite.", "cada bocado.")}</em></h2><p>{t("We are a family-owned restaurant with a simple belief: good food should make you feel welcome. Our Mexican dishes are made to order with the flavors and recipes that have brought people together for generations.", "Somos un restaurante familiar que cree que la buena comida debe hacerte sentir bienvenido. Preparamos nuestros platillos mexicanos al momento, con sabores y recetas que han unido a generaciones.")}</p><p>{t("For more than a decade, we have served our neighbors with the warmth of home.", "Por más de una década hemos recibido a nuestros vecinos con la calidez del hogar.")}</p><Link href={href("/about")} className="text-link">{t("Get to know us", "Conoce nuestra historia")} <ArrowUpRight size={18}/></Link></div></div></section>

    <section className="section menu-feature"><div className="shell"><SectionHeading eyebrow={`02 / ${t("A TASTE OF SAN ANTONIO", "UN SABOR DE SAN ANTONIO")}`} title={t("Come hungry. Leave happy.", "Ven con hambre. Vete feliz.")} text={t("A few favorites from our table. Explore the full selection and choose your neighborhood location for ordering.", "Algunos favoritos de nuestra mesa. Explora la selección y elige tu sucursal para ordenar.")} href={href("/menu")} action={t("View the menu", "Ver el menú")}/><div className="featured-grid">{featured.map((item, index) => { const photo = photoById.get(item.photoId); return <Link href={href("/menu")} className="featured-card" key={item.id}><div className="featured-image">{photo && <Image src={photo.src} alt={item.name} fill sizes="(max-width: 700px) 100vw, 33vw" />}</div><div className="featured-meta"><span>0{index + 1} / {categoryLabel(locale, item.category, menuCategoryLabels).toUpperCase()}</span><ArrowUpRight size={21}/></div><h3>{item.name}</h3></Link>; })}</div></div></section>

    <section className="photo-quote"><Image src="/images/menu/tacos-tacos-rancheros-de-bistec.webp" alt="Tacos Rancheros de Bistec" fill sizes="100vw"/><div className="photo-quote-overlay"/><div className="shell photo-quote-content"><Star size={25} fill="currentColor"/><span>{t("OUR KIND OF COMFORT FOOD", "COMIDA QUE NOS HACE SENTIR EN CASA")}</span><h2>{t("Made fresh.", "Recién hecho.")}<br/><em>{t("Made for you.", "Hecho para ti.")}</em></h2><Link href={href("/gallery")} className="button button-cream">{t("See the gallery", "Ver la galería")} <ArrowUpRight size={18}/></Link></div></section>

    <section className="section locations-section"><div className="shell"><SectionHeading eyebrow={`03 / ${t("FIND YOUR SAN ANTONIO", "ENCUENTRA TU SAN ANTONIO")}`} title={t("Three places to gather.", "Tres lugares para reunirnos.")} text={t("Your neighborhood table is closer than you think.", "Tu mesa está más cerca de lo que imaginas.")} href={href("/locations")} action={t("All locations", "Todas las sucursales")}/><div className="locations-grid">{locations.map((location, index) => <LocationCard key={location.slug} location={location} index={index} locale={locale}/>)}</div></div></section>

    <section className="catering-banner"><div className="shell catering-inner"><div><span className="eyebrow light">{t("BRING THE FLAVOR TO YOUR CELEBRATION", "LLEVA EL SABOR A TU CELEBRACIÓN")}</span><h2>{t("Let's make it", "Hagamos una")}<br/><em>{t("a fiesta.", "fiesta.")}</em></h2><p>{t("From family gatherings to special occasions, explore San Antonio party packages.", "Desde reuniones familiares hasta ocasiones especiales, conoce los paquetes para fiestas de San Antonio.")}</p><Link href={href("/catering")} className="button button-cream">{t("Explore catering", "Conoce los paquetes")} <ArrowUpRight size={18}/></Link></div><div className="catering-image"><Image src="/images/menu/platillos-parrillada-mixta.webp" alt="Parrillada Mixta" fill sizes="(max-width: 800px) 90vw, 40vw"/></div></div></section>
  </>;
}
