import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, MapPin, Phone, Clock3 } from "lucide-react";
import type { Location } from "@/data/locations";
import { photoById } from "@/data/photos";
import { hoursDays, localizedHref, tr, type Locale } from "@/data/i18n";

export function LocationContent({ location, locale }: { location: Location; locale: Locale }) {
  const hero = photoById.get(location.galleryIds[0]);
  const t = (english: string, spanish: string) => tr(locale, english, spanish);
  return <><section className="location-hero"><div className="location-hero-image">{hero && <Image src={hero.src} alt={hero.title} fill priority sizes="100vw"/>}<div className="hero-shade"/></div><div className="shell location-hero-content"><Link href={localizedHref(locale, "/locations")}>← {t("All locations", "Todas las sucursales")}</Link><span className="eyebrow light">{location.neighborhood.toUpperCase()}</span><h1>{location.name}</h1><p>{location.address}, {location.city}</p></div></section><section className="section"><div className="shell location-detail-grid"><div><span className="eyebrow">{t("COME ON IN", "VEN A VISITARNOS")}</span><h2>{t("Your table is waiting.", "Tu mesa te espera.")}</h2><p>{t("Find us in the neighborhood, enjoy a meal, or order your favorites online.", "Visítanos, disfruta de una comida u ordena tus favoritos en línea.")}</p><div className="location-detail-actions"><a className="button button-dark" href={location.orderUrl} target="_blank" rel="noopener noreferrer">{t("Order online", "Ordenar en línea")} <ArrowUpRight size={18}/></a><a className="button button-outline" href={location.mapUrl} target="_blank" rel="noopener noreferrer">{t("Get directions", "Cómo llegar")} <ArrowUpRight size={18}/></a></div></div><div className="location-facts"><div><MapPin/><h3>{t("Address", "Dirección")}</h3><p>{location.address}<br/>{location.city}</p></div><div><Phone/><h3>{t("Call us", "Llámanos")}</h3><a href={`tel:${location.tel}`}>{location.phone}</a></div><div><Clock3/><h3>{t("Hours", "Horarios")}</h3>{location.hours.map(row => <p key={row.days}>{hoursDays(locale, row.days)}<br/><strong>{row.time}</strong></p>)}</div></div></div></section><section className="section warm-section"><div className="shell"><span className="eyebrow">{t("A TASTE OF THIS LOCATION", "UN SABOR DE ESTA SUCURSAL")}</span><h2>{t("From our kitchen.", "De nuestra cocina.")}</h2><p className="source-note">{t("Restaurant photographs supplied by the client. Individual branch attribution for these images has not been confirmed.", "Fotografías del restaurante proporcionadas por el cliente. Aún no se ha confirmado a qué sucursal pertenece cada imagen.")}</p><div className="location-gallery">{location.galleryIds.map(id => {const photo=photoById.get(id); return photo && <div key={id}><Image src={photo.src} alt={photo.title} fill sizes="(max-width: 700px) 90vw, 33vw"/><span>{photo.title}</span></div>;})}</div></div></section></>;
}
