import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Clock3, MapPin, Phone } from "lucide-react";
import { Gallery } from "@/components/gallery";
import { MenuBrowser } from "@/components/menu-browser";
import { LocationCard } from "@/components/location-card";
import { locations } from "@/data/locations";
import { photos, galleryCategories } from "@/data/photos";
import { media } from "@/data/media";
import { hoursDays, localizedHref, tr, type Locale } from "@/data/i18n";
import { sectionCopy, type Section } from "@/data/sections";

const packages = [
  { n: "01", price: "$200", en: { name: "Chivo gathering", detail: "Half tray of chivo, half tray of rice, half tray of salad and one portion of consomé." }, es: { name: "Reunión con chivo", detail: "Media charola de chivo, media charola de arroz, media charola de ensalada y una porción de consomé." } },
  { n: "02", price: "$340", en: { name: "Chivo celebration", detail: "One tray of chivo, one tray of rice, one tray of salad and one portion of consomé." }, es: { name: "Celebración con chivo", detail: "Una charola de chivo, una de arroz, una de ensalada y una porción de consomé." } },
  { n: "03", price: "$615", en: { name: "Large chivo celebration", detail: "Two trays of chivo, half tray of rice, one tray of salad and two portions of consomé." }, es: { name: "Gran celebración con chivo", detail: "Dos charolas de chivo, media charola de arroz, una de ensalada y dos porciones de consomé." } },
  { n: "04", price: "$130", en: { name: "Pernil gathering", detail: "One large pernil, half tray of rice, half tray of salad, salsa and a small portion of guacamole." }, es: { name: "Reunión con pernil", detail: "Un pernil grande, media charola de arroz, media de ensalada, salsa y una porción pequeña de guacamole." } },
  { n: "05", price: "$255", en: { name: "Pernil celebration", detail: "A tray with two perniles, half tray of rice, one tray of salad, a large portion of salsa and a large portion of guacamole." }, es: { name: "Celebración con pernil", detail: "Una charola con dos perniles, media charola de arroz, una de ensalada, una porción grande de salsa y una de guacamole." } },
];

function PageIntro({ section, locale }: { section: Section; locale: Locale }) {
  const copy = sectionCopy[section][locale];
  return <section className="page-intro"><div className="shell"><span className="eyebrow">SAN ANTONIO MEXICAN RESTAURANT / {copy.title.toUpperCase()}</span><h1>{copy.title}<span className="heading-spark">✳</span></h1><p>{copy.subtitle}</p></div></section>;
}

export function SectionContent({ section, locale }: { section: Section; locale: Locale }) {
  const t = (english: string, spanish: string) => tr(locale, english, spanish);
  const href = (path: string) => localizedHref(locale, path);
  return <><PageIntro section={section} locale={locale}/>
    {section === "about" && <><section className="section"><div className="shell about-grid"><div className="about-image"><Image src="/images/menu/platillos-molcajete-mixto.webp" alt="Molcajete Mixto" fill sizes="(max-width: 800px) 90vw, 45vw" /></div><div className="about-copy"><span className="eyebrow">{t("FAMILY OWNED · ROOTED IN FLAVOR", "NEGOCIO FAMILIAR · CON RAÍCES EN EL SABOR")}</span><h2>{t("A story served at the table.", "Una historia que se sirve en la mesa.")}</h2><p>{t("San Antonio Mexican Restaurant is a family-owned business specializing in authentic Mexican cuisine and fresh, made-to-order dishes. The restaurant's recipes have been passed down through generations.", "San Antonio Mexican Restaurant es un negocio familiar especializado en comida mexicana auténtica y platillos frescos preparados al momento. Sus recetas han pasado de generación en generación.")}</p><p>{t("For more than 10 years, San Antonio has shared traditional Mexican flavors and the feeling of home with its guests.", "Por más de 10 años, San Antonio ha compartido sabores tradicionales de México y la calidez del hogar con sus visitantes.")}</p><Link href={href("/locations")} className="text-link">{t("Come visit us", "Ven a visitarnos")} <ArrowUpRight size={18}/></Link></div></div></section><section className="section warm-section"><div className="shell"><p className="big-quote">{t("The best meals are the ones", "Las mejores comidas son las que")} <em>{t("we share.", "compartimos.")}</em></p><div className="about-mosaic"><Image src="/images/menu/tacos-tacos-de-suadero.webp" alt="Tacos de suadero" fill sizes="50vw"/><Image src="/images/menu/desserts-chocoflan.webp" alt="Chocoflan" fill sizes="50vw"/></div></div></section></>}
    {section === "menu" && <section className="section"><div className="shell"><div className="menu-topline"><span className="eyebrow">{t("FRESHLY MADE · ALWAYS SHARED", "RECIÉN HECHO · PARA COMPARTIR")}</span><p>{t("Our menu has a little something for every craving. Prices below are a selection from each location's official online menu.", "Nuestro menú tiene algo para cada antojo. Los precios mostrados son una selección de los menús oficiales de pedidos de cada sucursal.")}</p></div><MenuBrowser locale={locale}/></div></section>}
    {section === "gallery" && <section className="section"><div className="shell"><div className="menu-topline"><span className="eyebrow">{t("THE COLORS OF OUR KITCHEN", "LOS COLORES DE NUESTRA COCINA")}</span><p>{t(`${photos.length} original restaurant photographs, from breakfast to dessert.`, `${photos.length} fotografías originales del restaurante, desde desayunos hasta postres.`)}</p></div><Gallery photos={photos} categories={galleryCategories} locale={locale}/></div></section>}
    {section === "locations" && <section className="section"><div className="shell"><div className="locations-grid">{locations.map((location, index) => <LocationCard key={location.slug} location={location} index={index} locale={locale}/>)}</div></div></section>}
    {section === "order-online" && <section className="section"><div className="shell"><div className="order-intro"><span className="eyebrow">{t("YOUR FAVORITES, YOUR WAY", "TUS FAVORITOS, A TU MANERA")}</span><h2>{t("Choose your location.", "Elige tu sucursal.")}</h2><p>{t("Ordering opens each restaurant's official online menu in a new tab. Availability and prices are set by that location.", "Al ordenar se abre el menú oficial de cada sucursal en una pestaña nueva. La disponibilidad y los precios dependen de esa ubicación.")}</p></div><div className="order-grid">{locations.map((location, index) => <article key={location.slug} className="order-card"><span>0{index + 1} / {location.neighborhood}</span><h3>{location.name}</h3><p>{location.address}<br/>{location.city}</p><a href={location.orderUrl} target="_blank" rel="noopener noreferrer" className="button button-dark">{t("Order from", "Ordenar en")} {location.name.replace("San Antonio ", "")} <ArrowUpRight size={18}/></a></article>)}</div></div></section>}
    {section === "catering" && <><section className="section"><div className="shell catering-page-grid"><div><span className="eyebrow">{t("FOOD FOR THE WHOLE FIESTA", "COMIDA PARA TODA LA FIESTA")}</span><h2>{t("Make every gathering memorable.", "Haz memorable cada reunión.")}</h2><p>{t("San Antonio offers party packages with chivo or pernil, rice, salad and accompaniments. The official promotions page requests at least five days' notice.", "San Antonio ofrece paquetes para fiestas con chivo o pernil, arroz, ensalada y acompañamientos. La página oficial solicita al menos cinco días de anticipación.")}</p><a href="#party-packages" className="button button-dark">{t("View party packages", "Ver paquetes para fiestas")} <ArrowUpRight size={18}/></a></div><div className="catering-page-image"><Image src="/images/menu/platillos-parrillada-mixta.webp" alt="Parrillada Mixta" fill sizes="(max-width: 800px) 90vw, 50vw" /></div></div></section><section id="party-packages" className="section warm-section"><div className="shell"><span className="eyebrow">{t("PARTY PACKAGES", "PAQUETES PARA FIESTAS")}</span><h2>{t("Something for every gathering.", "Un paquete para cada reunión.")}</h2><div className="package-grid">{packages.map(pkg => <article className="package-card" key={pkg.n}><span>{t("PACKAGE", "PAQUETE")} / {pkg.n}</span><h3>{pkg[locale].name}</h3><p>{pkg[locale].detail}</p><strong>{pkg.price}</strong></article>)}</div><p className="source-note">{t("Package details and listed prices are from the restaurant's official promotions page. Confirm current availability and final pricing with the restaurant.", "Los detalles y precios publicados provienen de la página oficial de promociones. Confirma disponibilidad y precio final con el restaurante.")}</p></div></section></>}
    {section === "reservations" && <section className="section"><div className="shell reservation-layout"><div><span className="eyebrow">{t("SAVE A SEAT", "PLANEA TU VISITA").toUpperCase()}</span><h2>{t("Let's get together.", "Reunámonos.")}</h2><p>{t("For table availability and group visits, please call the location you plan to visit. An online reservation system has not been confirmed.", "Para consultar disponibilidad de mesas y visitas en grupo, llama a la sucursal que deseas visitar. No se ha confirmado un sistema de reservaciones en línea.")}</p></div><div className="reservation-list">{locations.map(location => <div key={location.slug}><h3>{location.name}</h3><span>{location.address}, {location.city}</span><a href={`tel:${location.tel}`}><Phone size={17}/>{location.phone}</a></div>)}</div></div></section>}
    {section === "contact" && <section className="section"><div className="shell contact-layout"><div><span className="eyebrow">{t("GET IN TOUCH", "CONTÁCTANOS")}</span><h2>{t("We're here for you.", "Estamos para ayudarte.")}</h2><p>{t("Questions about a visit, an order or a gathering? Contact your preferred restaurant directly.", "¿Tienes preguntas sobre una visita, un pedido o una reunión? Comunícate directamente con tu sucursal preferida.")}</p><Link href={href("/locations")} className="text-link">{t("Explore our locations", "Explora nuestras sucursales")} <ArrowUpRight size={18}/></Link></div><div className="contact-list">{locations.map(location => <article key={location.slug}><h3>{location.name}</h3><p><MapPin size={18}/>{location.address}, {location.city}</p><p><Clock3 size={18}/>{location.hours.map(h => `${hoursDays(locale, h.days)}: ${h.time}`).join(" · ")}</p><a href={`tel:${location.tel}`}><Phone size={18}/>{location.phone}</a></article>)}</div></div></section>}
    {media.promotionalVideo && (section === "about" || section === "gallery") && <section className="section"><div className="shell"><video className="promo-video" controls playsInline preload="none" poster="/images/menu/platillos-parrillada-mixta.webp"><source src={media.promotionalVideo} type="video/mp4"/></video></div></section>}
  </>;
}
